---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: main
    rebase-strategy: auto
    schedule:
      interval: monthly
    assignees:
      - georglauterbach
    labels:
      - area/ci
      - kind/update
